import { mkdir, writeFile } from 'node:fs/promises'
import { pathToFileURL } from 'node:url'
const { chromium } = await import(pathToFileURL(process.argv[2]).href)
const out = 'test-results/figma-discovery'
await mkdir(out, { recursive: true })
const browser = await chromium.launch({ channel: 'chrome', headless: true })
let page = await browser.newPage({ viewport: { width: 1280, height: 900 } })
const states = []
async function capture(name) {
  await page.waitForTimeout(450)
  await page.screenshot({ path: `${out}/${name}.png`, fullPage: true })
  states.push({ name, text: await page.locator('body').innerText() })
}
try {
  await page.goto('https://morph-byte-72870981.figma.site', { timeout: 25000 })
  await capture('published')
} catch (error) { states.push({ name: 'published', error: String(error) }) }
await page.close()
page = await browser.newPage({ viewport: { width: 1280, height: 900 } })
await page.goto('http://127.0.0.1:5174')
await capture('splash')
if (await page.getByRole('button', { name: 'Start exploring' }).isVisible()) await page.getByRole('button', { name: 'Start exploring' }).click()
await capture('camera-demo')
await page.getByRole('button', { name: 'Capture this view', exact: true }).click()
await capture('scanning')
await page.locator('.hotspot').first().waitFor()
await capture('discovered')
await page.locator('.hotspot').first().click()
await capture('object')
await page.getByRole('button', { name: 'Care for it', exact: true }).click()
await capture('object-action')
await page.getByRole('button', { name: 'Ask something', exact: true }).click()
await capture('ask')
await page.getByRole('button', { name: 'Speak your request' }).click()
await page.waitForTimeout(700)
await capture('voice')
await page.getByRole('button', { name: 'Hear from my things' }).click()
await capture('response')
await page.getByRole('button', { name: 'Close panel' }).click()
await page.getByRole('button', { name: 'Find', exact: true }).click()
if (await page.getByRole('button', { name: 'Capture this view', exact: true }).isVisible()) await page.getByRole('button', { name: 'Capture this view', exact: true }).click()
await page.getByRole('textbox').fill('charge my phone')
await page.getByRole('button', { name: 'Find it in my space' }).click()
await capture('found')
await page.getByRole('button', { name: 'Fix', exact: true }).click()
await page.getByRole('button', { name: 'Open first problem' }).click()
await capture('fix')
await page.getByRole('button', { name: 'Improve', exact: true }).click()
await capture('improve')
await page.getByRole('button', { name: 'How it works' }).click()
await capture('help')
await page.getByRole('button', { name: 'Preview error state' }).click()
await capture('error')
await page.locator('input[type=file]').setInputFiles('test-images/blank.png')
await page.waitForTimeout(2500)
await capture('blank-upload-still-fake-hotspots')
await page.setViewportSize({ width: 390, height: 844 })
await page.getByRole('button', { name: 'Explore', exact: true }).click()
await page.locator('.hotspot').first().click()
await capture('mobile-object')
// Source mobile close is overlapped by object-head; leave through navigation.
states.push({ name: 'mobile-close-source-bug', text: 'Close panel click intercepted by object-head; navigate via Explore instead.' })
await page.getByRole('button', { name: 'Explore', exact: true }).click()
await page.getByRole('button', { name: 'Use device camera' }).click()
await capture('camera-permission')
await writeFile(`${out}/states.json`, JSON.stringify(states, null, 2))
console.log(JSON.stringify(states.map(({ name, error }) => ({ name, error }))))
await browser.close()
